# Generated by Django 4.1.3 on 2023-01-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('startTimeUtc', models.DateTimeField()),
                ('endTimeUtc', models.DateTimeField()),
                ('isAllDay', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=30)),
                ('update', models.DateTimeField()),
                ('createdBy', models.IntegerField()),
                ('decryption', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
