# Generated by Django 4.1.3 on 2023-01-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_attendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userCreatedId', models.IntegerField()),
                ('eventId', models.IntegerField()),
                ('listUser', models.JSONField()),
            ],
        ),
    ]
