# Generated by Django 4.1.3 on 2023-01-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='eAttendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('userCreatedId', models.IntegerField()),
                ('eventId', models.IntegerField()),
                ('listUser', models.JSONField()),
            ],
        ),
    ]
