# Generated by Django 4.1.3 on 2023-01-27 05:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eattendee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event_attendee',
        ),
        migrations.AlterField(
            model_name='eattendee',
            name='listUser',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
